import { createQrDataUrl, createTicketPdf } from "./ticket-tools.js?v=10";

const API_BASE = "https://southamerica-east1-vendas-76f49.cloudfunctions.net";
const money = new Intl.NumberFormat("pt-BR", { style:"currency", currency:"BRL" });
const state = { event:null, promoterId:new URLSearchParams(location.search).get("promoter") || "", quantities:new Map(), checkout:null, brick:null, order:null, pollTimer:null };
const $ = (id) => document.getElementById(id);
const escapeHtml = (value) => String(value ?? "").replace(/[&<>'"]/g, (char) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "'":"&#39;", '"':"&quot;" })[char]);
function feeAmount(subtotal) { const fee=state.event?.buyerFee || {}; const amount=fee.mode==="percent"?subtotal*Number(fee.value||0)/100:fee.mode==="fixed"?Number(fee.value||0):0; return Math.round(Math.max(0,amount)*100)/100; }
function selectedItems(){return (state.event?.ticketTypes||[]).map((ticket)=>({...ticket,quantity:Number(state.quantities.get(ticket.id)||0)})).filter((ticket)=>ticket.quantity>0);}
function totals(){const items=selectedItems();const subtotal=Math.round(items.reduce((sum,item)=>sum+Number(item.price||0)*item.quantity,0)*100)/100;const fee=feeAmount(subtotal);return{items,subtotal,fee,total:Math.round((subtotal+fee)*100)/100};}
function renderSummary(){const current=totals();$("storeSummaryItems").innerHTML=current.items.length?current.items.map((item)=>`<div class="summary-item"><span>${item.quantity}× ${escapeHtml(item.name)}</span><strong>${money.format(item.price*item.quantity)}</strong></div>`).join(""):'<div class="summary-item"><span>Nenhum ingresso selecionado</span></div>';$("storeSubtotal").textContent=money.format(current.subtotal);$("storeFeeLine").hidden=current.fee<=0;$("storeFee").textContent=money.format(current.fee);$("storeTotal").textContent=money.format(current.total);$("continueToPayment").disabled=!current.items.length;}
function renderEvent(){const event=state.event;document.title=`${event.name} | Ingressos`;$("storeEventName").textContent=event.name;$("storeEventMeta").textContent=`${event.dateLabel}${event.time?` às ${event.time}`:""} · ${event.place}`;$("storeTicketTypes").innerHTML=event.ticketTypes.map((ticket)=>`<article class="store-ticket" data-ticket="${escapeHtml(ticket.id)}"><div><strong>${escapeHtml(ticket.name)}</strong><small><span class="ticket-price">${money.format(ticket.price)}</span> · ${ticket.available} disponíveis</small></div><div class="quantity-control"><button type="button" data-quantity="-1" aria-label="Diminuir">−</button><output>0</output><button type="button" data-quantity="1" aria-label="Aumentar" ${ticket.available<1?"disabled":""}>+</button></div></article>`).join("");$("storeContent").hidden=false;$("storeLoading").hidden=true;renderSummary();}
async function loadEvent(){const slug=new URLSearchParams(location.search).get("evento")||location.hostname;try{const response=await fetch(`${API_BASE}/publicEvent?slug=${encodeURIComponent(slug)}&host=${encodeURIComponent(location.hostname)}`);const data=await response.json();if(!response.ok)throw new Error(data.error||"Evento indisponível.");state.event=data.event;renderEvent();}catch(error){$("storeLoading").hidden=true;$("storeError").hidden=false;$("storeError").querySelector("small").textContent=error.message;}}
async function prepareCheckout(){const buyer={name:$("storeBuyerName").value.trim(),email:$("storeBuyerEmail").value.trim(),phone:$("storeBuyerPhone").value.trim()};if(!buyer.name)return $("storeBuyerName").reportValidity();if(!$("storeBuyerEmail").checkValidity())return $("storeBuyerEmail").reportValidity();const button=$("continueToPayment");button.disabled=true;button.textContent="Confirmando disponibilidade...";try{const response=await fetch(`${API_BASE}/prepareOnlineCheckout`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({eventId:state.event.id,promoterId:state.promoterId,items:selectedItems().map(({id,quantity})=>({ticketTypeId:id,quantity})),buyer})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Não foi possível preparar o pagamento.");state.checkout=data;await renderPaymentBrick(data);$("paymentSection").hidden=false;$("paymentSection").scrollIntoView({behavior:"smooth",block:"start"});}catch(error){alert(error.message);button.disabled=false;button.textContent="Continuar para pagamento";}}
async function renderPaymentBrick(checkout){if(state.brick){await state.brick.unmount();state.brick=null;}const mp=new MercadoPago(checkout.publicKey,{locale:"pt-BR"});const builder=mp.bricks();state.brick=await builder.create("payment","paymentBrick_container",{initialization:{amount:Number(checkout.total),payer:{email:checkout.buyerEmail}},customization:{paymentMethods:{bankTransfer:"all",creditCard:"all",debitCard:"all",prepaidCard:"all",maxInstallments:12}},callbacks:{onReady:()=>{},onError:(error)=>console.error(error),onSubmit:({selectedPaymentMethod,formData})=>submitPayment(selectedPaymentMethod,formData)}});}
async function submitPayment(selectedPaymentMethod,formData){const response=await fetch(`${API_BASE}/createOnlineOrder`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({checkoutId:state.checkout.checkoutId,checkoutToken:state.checkout.checkoutToken,selectedPaymentMethod,formData})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Pagamento não concluído.");showResult(data);}
function showResult(data){$("paymentSection").hidden=true;$("paymentResult").hidden=false;const approved=Boolean(data.paid)||(data.status==="processed"&&data.statusDetail==="accredited");$("paymentResultTitle").textContent=approved?"Pagamento aprovado":"Pagamento iniciado";$("paymentResultMessage").textContent=approved?"Sua compra foi confirmada. Seus ingressos estão disponíveis abaixo.":"Conclua o pagamento. Esta página atualizará a confirmação automaticamente.";if(data.pix?.qrCode){$("pixResult").hidden=false;$("pixQrCode").src=data.pix.qrCodeBase64?.startsWith("data:")?data.pix.qrCodeBase64:`data:image/png;base64,${data.pix.qrCodeBase64||""}`;$("pixCopyCode").value=data.pix.qrCode;}$("paymentResult").scrollIntoView({behavior:"smooth"});startOrderPolling();}
async function loadOrderStatus(){if(!state.checkout)return null;const response=await fetch(`${API_BASE}/onlineOrderStatus?checkoutId=${encodeURIComponent(state.checkout.checkoutId)}&checkoutToken=${encodeURIComponent(state.checkout.checkoutToken)}`);const data=await response.json();if(!response.ok)throw new Error(data.error||"Não foi possível consultar o pedido.");state.order=data;if(data.paid)await renderOrderTickets(data);return data;}
function startOrderPolling(){clearTimeout(state.pollTimer);let attempts=0;const poll=async()=>{attempts+=1;try{const order=await loadOrderStatus();if(order?.paid){$("paymentResultTitle").textContent="Pagamento aprovado";$("paymentResultMessage").textContent="Sua compra foi confirmada. Seus ingressos estão disponíveis abaixo.";$("pixResult").hidden=true;return;}}catch(error){console.warn(error);}if(attempts<150)state.pollTimer=setTimeout(poll,4000);};poll();}
function generatedAtText(timestamp){return new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(timestamp));}
function paymentLabel(method){return ({pix:"Pix",credit_card:"Cartão de crédito",debit_card:"Cartão de débito"})[method]||"Mercado Pago";}
function pdfTickets(order){return order.tickets.map((ticket)=>({eventName:order.event.name,participantName:ticket.participantName,admissionType:"INGRESSO INDIVIDUAL",ticketTypeName:ticket.ticketTypeName,eventDate:`${order.event.dateLabel}${order.event.time?` às ${order.event.time}`:""}`,eventPlace:order.event.place,ticketValue:money.format(ticket.value),paymentStatus:"PAGO",paymentDetail:paymentLabel(order.paymentMethod),shortCode:ticket.shortCode,validationUrl:ticket.validationUrl,generatedByName:ticket.generatedByName,generatedAtText:generatedAtText(ticket.generatedAt)}));}
async function renderOrderTickets(order){const container=$("orderTickets");const rendered=await Promise.all(order.tickets.map(async(ticket)=>`<article class="online-ticket"><img src="${await createQrDataUrl(ticket.validationUrl,{width:360})}" alt="QR Code de ${escapeHtml(ticket.participantName)}"><div><small>${escapeHtml(ticket.ticketTypeName)}</small><strong>${escapeHtml(ticket.participantName)}</strong><code>${escapeHtml(ticket.shortCode)}</code></div></article>`));container.innerHTML=`<h3>Seus ingressos</h3>${rendered.join("")}`;container.hidden=false;$("downloadOrderPdf").hidden=false;}
async function downloadOrderPdf(){if(!state.order?.paid)return;const button=$("downloadOrderPdf");button.disabled=true;button.textContent="Gerando PDF...";try{const blob=await createTicketPdf(pdfTickets(state.order),state.order.event.ticketDesign);const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`ingressos-${String(state.order.event.name||"evento").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/gi,"-").replace(/^-|-$/g,"").toLowerCase()}.pdf`;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),30000);}finally{button.disabled=false;button.textContent="Baixar ingressos em PDF";}}
$("storeTicketTypes").addEventListener("click",(event)=>{const button=event.target.closest("[data-quantity]");if(!button)return;const card=button.closest("[data-ticket]");const ticket=state.event.ticketTypes.find((item)=>item.id===card.dataset.ticket);const next=Math.max(0,Math.min(ticket.available,Number(state.quantities.get(ticket.id)||0)+Number(button.dataset.quantity)));state.quantities.set(ticket.id,next);card.querySelector("output").textContent=String(next);renderSummary();});
$("continueToPayment").addEventListener("click",prepareCheckout);$("copyPixCode").addEventListener("click",async()=>{await navigator.clipboard.writeText($("pixCopyCode").value);$("copyPixCode").textContent="Código copiado";});$("downloadOrderPdf").addEventListener("click",downloadOrderPdf);$("newPurchase").addEventListener("click",()=>location.reload());
loadEvent();
